version = 1

[[annotations]]
path = "3rdparty/icons/breeze/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 Uri Herrera <uri_herrera@nitrux.in>"
SPDX-License-Identifier = "LGPL-3.0-or-later"

[[annotations]]
path = "3rdparty/icons/breeze-dark/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 Uri Herrera <uri_herrera@nitrux.in>"
SPDX-License-Identifier = "LGPL-3.0-or-later"

[[annotations]]
path = "3rdparty/icons/oxygen/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2007 Nuno Pinheiro <nuno@oxygen-icons.org>; 2007 David Vignoni <david@icon-king.com>; David Miller <miller@oxygen-icons.org>; 2007 Johann Ollivier Lapeyre <johann@oxygen-icons.org>; 2007 Kenneth Wimer <kwwii@bootsplash.org>; 2007 Riccardo Iaconelli <riccardo@oxygen-icons.org>;"
SPDX-License-Identifier = "LGPL-3.0-or-later"

# Configuration files
[[annotations]]
path = [".gitignore", ".gitmodules", ".gitattributes"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2005-2025 Quassel Project <devel@quassel-irc.org"
SPDX-License-Identifier = "GPL-2.0-or-later"

# Qt UI things which may be modified by Qt Creator
[[annotations]]
path = "src/qtui/**/*.ui"
precedence = "aggregate"
SPDX-FileCopyrightText = "2005-2025 Quassel Project <devel@quassel-irc.org"
SPDX-License-Identifier = "GPL-2.0-or-later"